<?php
// --- 1. SECURITY CHECK & CSRF TOKEN GENERATION ---
if (!isset($_SESSION['user_id']) || !in_array('Admin', $_SESSION['roles'])) {
    header('Location: ' . BASE_URL);
    exit();
}
// This function is now called globally from config.php, so no need to call it here.

// --- 2. MASTER POST HANDLER ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Validate the CSRF token on every POST request to this page.
    validate_csrf_token();

    $action = $_POST['action'] ?? '';
    switch ($action) {
        case 'add_news': if (!empty($_POST['title'])&&!empty($_POST['body'])){$stmt=$conn->prepare("INSERT INTO news (title, author, body, image_url) VALUES (?, ?, ?, ?)");$stmt->bind_param("ssss",$_POST['title'],$_SESSION['display_name'],$_POST['body'],$_POST['image_url']);if($stmt->execute())set_flash_message('Article published!','success');else set_flash_message('Error.','error');$stmt->close();}else{set_flash_message('Title and Body are required.','error');}header('Location: '.BASE_URL.'admin?view=news');exit();
        case 'update_news': if (!empty($_POST['title'])&&!empty($_POST['body'])&&!empty($_POST['id'])){$stmt=$conn->prepare("UPDATE news SET title = ?, body = ?, image_url = ? WHERE id = ?");$stmt->bind_param("sssi",$_POST['title'],$_POST['body'],$_POST['image_url'],$_POST['id']);if($stmt->execute())set_flash_message('Article updated.','success');else set_flash_message('Error.','error');$stmt->close();}header('Location: '.BASE_URL.'admin?view=news');exit();
        case 'delete_news': if(!empty($_POST['id'])){$stmt=$conn->prepare("DELETE FROM news WHERE id = ?");$stmt->bind_param("i",$_POST['id']);if($stmt->execute())set_flash_message('Article deleted.','success');else set_flash_message('Error.','error');$stmt->close();}header('Location: '.BASE_URL.'admin?view=news');exit();
        case 'add_role': if(!empty($_POST['role_name'])){$stmt=$conn->prepare("INSERT INTO roles (name) VALUES (?)");$stmt->bind_param("s",$_POST['role_name']);if($stmt->execute())set_flash_message('Role created.','success');else set_flash_message('Error.','error');$stmt->close();}header('Location: '.BASE_URL.'admin?view=users');exit();
        case 'delete_role': if(!empty($_POST['id'])){$role_id_to_delete=(int)$_POST['id'];$member_role_id=3;$conn->begin_transaction();try{$stmt_cleanup=$conn->prepare("DELETE FROM user_roles WHERE role_id = ? AND user_id IN (SELECT user_id FROM (SELECT user_id FROM user_roles WHERE role_id = ?) AS subquery)");$stmt_cleanup->bind_param("ii",$role_id_to_delete,$member_role_id);$stmt_cleanup->execute();$stmt_cleanup->close();$stmt_reassign=$conn->prepare("UPDATE user_roles SET role_id = ? WHERE role_id = ?");$stmt_reassign->bind_param("ii",$member_role_id,$role_id_to_delete);$stmt_reassign->execute();$stmt_reassign->close();$stmt_delete=$conn->prepare("DELETE FROM roles WHERE id = ?");$stmt_delete->bind_param("i",$role_id_to_delete);$stmt_delete->execute();$stmt_delete->close();$conn->commit();set_flash_message('Role deleted.','success');}catch(mysqli_sql_exception $e){$conn->rollback();set_flash_message('Error.','error');}}header('Location: '.BASE_URL.'admin?view=users');exit();
        case 'update_user_roles': if(!empty($_POST['user_id'])){$user_id_to_edit=(int)$_POST['user_id'];$posted_role_ids=$_POST['roles']??[];$conn->begin_transaction();try{$stmt_delete=$conn->prepare("DELETE FROM user_roles WHERE user_id = ?");$stmt_delete->bind_param("i",$user_id_to_edit);$stmt_delete->execute();$stmt_delete->close();if(!empty($posted_role_ids)){$stmt_insert=$conn->prepare("INSERT INTO user_roles (user_id, role_id) VALUES (?, ?)");foreach($posted_role_ids as $role_id){$stmt_insert->bind_param("ii",$user_id_to_edit,$role_id);$stmt_insert->execute();}$stmt_insert->close();}$conn->commit();set_flash_message('Roles updated.','success');}catch(mysqli_sql_exception $e){$conn->rollback();set_flash_message('Error.','error');}}header('Location: '.BASE_URL.'admin?view=users');exit();
        case 'add_download': if(!empty($_POST['project_name'])&&!empty($_POST['version'])&&isset($_FILES['download_file'])&&$_FILES['download_file']['error']==0){$target_dir=$_SERVER['DOCUMENT_ROOT'].'/releases/';$safe_filename=time().'_'.basename(preg_replace("/[^a-zA-Z0-9\._-]/","",$_FILES["download_file"]["name"]));$target_file=$target_dir.$safe_filename;if(move_uploaded_file($_FILES["download_file"]["tmp_name"],$target_file)){$stmt=$conn->prepare("INSERT INTO downloads (project_name,version,description,file_path,file_size) VALUES (?,?,?,?,?)");$file_size=$_FILES['download_file']['size'];$stmt->bind_param("ssssi",$_POST['project_name'],$_POST['version'],$_POST['description'],$safe_filename,$file_size);if($stmt->execute()){set_flash_message('Download uploaded successfully!','success');}else{set_flash_message('Database error.','error');unlink($target_file);}$stmt->close();}else{set_flash_message('Error uploading file.','error');}}else{set_flash_message('Project Name, Version, and a File are required.','error');}header('Location: '.BASE_URL.'admin?view=downloads');exit();
        case 'delete_download': if(!empty($_POST['id'])){$stmt_get=$conn->prepare("SELECT file_path FROM downloads WHERE id = ?");$stmt_get->bind_param("i",$_POST['id']);$stmt_get->execute();$result=$stmt_get->get_result();if($result->num_rows===1){$file_path=$result->fetch_assoc()['file_path'];$full_file_path=$_SERVER['DOCUMENT_ROOT'].'/releases/'.$file_path;$stmt_del=$conn->prepare("DELETE FROM downloads WHERE id = ?");$stmt_del->bind_param("i",$_POST['id']);if($stmt_del->execute()){if(file_exists($full_file_path)){unlink($full_file_path);}set_flash_message('Download deleted.','success');}else{set_flash_message('Error deleting record.','error');}$stmt_del->close();}else{set_flash_message('Record not found.','error');}$stmt_get->close();}header('Location: '.BASE_URL.'admin?view=downloads');exit();
    }
}

// --- 3. VIEW ROUTER & DATA FETCHING (with Pagination) ---
$view = $_GET['view'] ?? 'stats';
$items_per_page = 10;
switch ($view) {
    case 'stats': $user_count = $conn->query("SELECT COUNT(id) AS count FROM users")->fetch_assoc()['count']; $news_count = $conn->query("SELECT COUNT(id) AS count FROM news")->fetch_assoc()['count']; $role_count = $conn->query("SELECT COUNT(id) AS count FROM roles")->fetch_assoc()['count']; $download_count = $conn->query("SELECT COUNT(id) AS count FROM downloads")->fetch_assoc()['count']; break;
    case 'news': $current_page = isset($_GET['p']) && is_numeric($_GET['p']) ? (int)$_GET['p'] : 1; $total_items_res = $conn->query("SELECT COUNT(id) AS total FROM news"); $total_items = $total_items_res->fetch_assoc()['total']; $total_pages = ceil($total_items / $items_per_page); $offset = ($current_page - 1) * $items_per_page; $stmt = $conn->prepare("SELECT id, title, author, publish_date FROM news ORDER BY publish_date DESC LIMIT ? OFFSET ?"); $stmt->bind_param("ii", $items_per_page, $offset); $stmt->execute(); $news_articles_res = $stmt->get_result(); $stmt->close(); break;
    case 'edit-news': $article = null; if (isset($_GET['id'])) { $stmt = $conn->prepare("SELECT id, title, body, image_url FROM news WHERE id = ?"); $stmt->bind_param("i", $_GET['id']); $stmt->execute(); $article = $stmt->get_result()->fetch_assoc(); $stmt->close(); } break;
    case 'users': $current_page = isset($_GET['p']) && is_numeric($_GET['p']) ? (int)$_GET['p'] : 1; $total_items_res = $conn->query("SELECT COUNT(id) AS total FROM users"); $total_items = $total_items_res->fetch_assoc()['total']; $total_pages = ceil($total_items / $items_per_page); $offset = ($current_page - 1) * $items_per_page; $sql_users = "SELECT u.id, u.display_name, u.email, GROUP_CONCAT(r.name SEPARATOR ', ') AS roles FROM users u LEFT JOIN user_roles ur ON u.id = ur.user_id LEFT JOIN roles r ON ur.role_id = r.id GROUP BY u.id ORDER BY u.display_name LIMIT ? OFFSET ?"; $stmt = $conn->prepare($sql_users); $stmt->bind_param("ii", $items_per_page, $offset); $stmt->execute(); $users_res = $stmt->get_result(); $stmt->close(); $all_roles_res = $conn->query("SELECT id, name FROM roles ORDER BY name"); break;
    case 'downloads': $downloads_res = $conn->query("SELECT * FROM downloads ORDER BY upload_date DESC"); break;
    case 'delete-news': $article_title='this article'; if(isset($_GET['id'])){$stmt=$conn->prepare("SELECT title FROM news WHERE id=?");$stmt->bind_param("i",$_GET['id']);$stmt->execute();$res=$stmt->get_result();if($res->num_rows==1){$article_title=$res->fetch_assoc()['title'];}$stmt->close();} break;
    case 'delete-role': $role_name='this role'; if(isset($_GET['id'])){$stmt=$conn->prepare("SELECT name FROM roles WHERE id=?");$stmt->bind_param("i",$_GET['id']);$stmt->execute();$res=$stmt->get_result();if($res->num_rows==1){$role_name=$res->fetch_assoc()['name'];}$stmt->close();} break;
    case 'delete-download': $download_info = 'this file'; if(isset($_GET['id']) && is_numeric($_GET['id'])){ $stmt = $conn->prepare("SELECT project_name, version FROM downloads WHERE id=?"); $stmt->bind_param("i", $_GET['id']); $stmt->execute(); $res = $stmt->get_result(); if($res->num_rows==1){ $dl = $res->fetch_assoc(); $download_info = $dl['project_name'] . ' (v' . $dl['version'] . ')'; } $stmt->close(); } break;
}
function generate_pagination_links($base_url, $current_page, $total_pages) { if ($total_pages <= 1) return ''; $html = '<nav aria-label="Page navigation"><ul class="pagination justify-content-center">'; $html .= '<li class="page-item ' . ($current_page <= 1 ? 'disabled' : '') . '"><a class="page-link" href="' . $base_url . '&p=' . ($current_page - 1) . '">Prev</a></li>'; for ($i = 1; $i <= $total_pages; $i++) { $html .= '<li class="page-item ' . ($i == $current_page ? 'active' : '') . '"><a class="page-link" href="' . $base_url . '&p=' . $i . '">' . $i . '</a></li>'; } $html .= '<li class="page-item ' . ($current_page >= $total_pages ? 'disabled' : '') . '"><a class="page-link" href="' . $base_url . '&p=' . ($current_page + 1) . '">Next</a></li>'; $html .= '</ul></nav>'; return $html; }
?>
<div class="row">
    <!-- Admin Sidebar -->
    <aside class="col-lg-3 mb-4 mb-lg-0">
        <div class="list-group">
            <a href="<?php echo BASE_URL; ?>admin?view=stats" class="list-group-item list-group-item-action <?php if($view === 'stats') echo 'active'; ?>"><i class="fas fa-tachometer-alt fa-fw me-2"></i>Dashboard</a>
            <a href="<?php echo BASE_URL; ?>admin?view=news" class="list-group-item list-group-item-action <?php if(in_array($view, ['news', 'edit-news', 'delete-news'])) echo 'active'; ?>"><i class="fas fa-newspaper fa-fw me-2"></i>News Management</a>
            <a href="<?php echo BASE_URL; ?>admin?view=downloads" class="list-group-item list-group-item-action <?php if(in_array($view, ['downloads', 'delete-download'])) echo 'active'; ?>"><i class="fas fa-download fa-fw me-2"></i>Downloads</a>
            <a href="<?php echo BASE_URL; ?>admin?view=users" class="list-group-item list-group-item-action <?php if(in_array($view, ['users', 'delete-role'])) echo 'active'; ?>"><i class="fas fa-users-cog fa-fw me-2"></i>User Management</a>
        </div>
    </aside>

    <!-- Main Admin Content -->
    <main class="col-lg-9">
        <?php display_flash_message(); ?>
        <?php // --- 4. DYNAMIC VIEW DISPLAY ---
        switch ($view):
            case 'stats': ?>
                <h2 class="mb-4">Dashboard</h2>
                <div class="row">
                    <div class="col-md-3 mb-4"><div class="card text-center h-100"><div class="card-body"><h3 class="display-4"><?php echo $user_count; ?></h3><p class="card-text text-muted">Total Users</p></div></div></div>
                    <div class="col-md-3 mb-4"><div class="card text-center h-100"><div class="card-body"><h3 class="display-4"><?php echo $news_count; ?></h3><p class="card-text text-muted">News Articles</p></div></div></div>
                    <div class="col-md-3 mb-4"><div class="card text-center h-100"><div class="card-body"><h3 class="display-4"><?php echo $role_count; ?></h3><p class="card-text text-muted">User Roles</p></div></div></div>
                    <div class="col-md-3 mb-4"><div class="card text-center h-100"><div class="card-body"><h3 class="display-4"><?php echo $download_count; ?></h3><p class="card-text text-muted">Total Downloads</p></div></div></div>
                </div>
            <?php break;
            case 'news': ?>
                <div class="card mb-4"><div class="card-header"><h4><i class="fas fa-plus-circle me-2"></i>Add New Article</h4></div><div class="card-body"><form action="<?php echo BASE_URL; ?>admin" method="POST"><input type="hidden" name="action" value="add_news"><?php csrf_input(); ?><div class="mb-3"><label for="title" class="form-label">Article Title</label><input type="text" class="form-control" id="title" name="title" required></div><div class="mb-3"><label for="image_url" class="form-label">Image URL (Optional)</label><input type="text" class="form-control" id="image_url" name="image_url" placeholder="https://example.com/image.jpg"></div><div class="mb-3"><label for="body" class="form-label">Body</label><textarea id="body" name="body" rows="10" class="form-control"></textarea></div><button type="submit" class="btn btn-warning"><i class="fas fa-paper-plane me-2"></i>Publish Article</button></form></div></div>
                <div class="card"><div class="card-header"><h4><i class="fas fa-list-alt me-2"></i>Manage Existing Articles</h4></div><div class="table-responsive"><table class="table table-hover table-striped mb-0"><thead><tr><th>Title</th><th>Author</th><th>Date</th><th>Actions</th></tr></thead><tbody>
                <?php while ($article = $news_articles_res->fetch_assoc()): ?><tr><td><?php echo htmlspecialchars($article['title']); ?></td><td><?php echo htmlspecialchars($article['author']); ?></td><td><?php echo date('M j, Y', strtotime($article['publish_date'])); ?></td><td><a href="<?php echo BASE_URL; ?>admin?view=edit-news&id=<?php echo $article['id']; ?>" class="btn btn-sm btn-primary"><i class="fas fa-edit"></i></a> <a href="<?php echo BASE_URL; ?>admin?view=delete-news&id=<?php echo $article['id']; ?>" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a></td></tr><?php endwhile; ?>
                </tbody></table></div>
                <?php if ($total_pages > 1): ?><div class="card-footer"><?php echo generate_pagination_links(BASE_URL . 'admin?view=news', $current_page, $total_pages); ?></div><?php endif; ?>
                </div>
            <?php break;
            case 'edit-news': if ($article): ?>
                <div class="card"><div class="card-header"><h4><i class="fas fa-edit me-2"></i>Edit News Article</h4></div><div class="card-body"><form action="<?php echo BASE_URL; ?>admin" method="POST"><input type="hidden" name="action" value="update_news"><?php csrf_input(); ?><input type="hidden" name="id" value="<?php echo $article['id']; ?>"><div class="mb-3"><label for="title" class="form-label">Article Title</label><input type="text" class="form-control" id="title" name="title" value="<?php echo htmlspecialchars($article['title']); ?>" required></div><div class="mb-3"><label for="image_url" class="form-label">Image URL (Optional)</label><input type="text" class="form-control" id="image_url" name="image_url" value="<?php echo htmlspecialchars($article['image_url'] ?? ''); ?>" placeholder="https://example.com/image.jpg"></div><div class="mb-3"><label for="body" class="form-label">Body</label><textarea id="body" name="body" rows="15" class="form-control"><?php echo htmlspecialchars($article['body']); ?></textarea></div><div class="d-flex justify-content-end gap-2"><a href="<?php echo BASE_URL; ?>admin?view=news" class="btn btn-secondary">Cancel</a><button type="submit" class="btn btn-warning"><i class="fas fa-save me-2"></i>Save Changes</button></div></form></div></div>
            <?php else: echo '<div class="alert alert-danger">Article not found.</div>'; endif; break;
            case 'delete-news': ?>
                <div class="card border-danger"><div class="card-header bg-danger text-white"><h4><i class="fas fa-exclamation-triangle me-2"></i>Confirm Deletion</h4></div><div class="card-body"><p>Are you sure you want to permanently delete the article: <strong><?php echo htmlspecialchars($article_title); ?></strong>?</p><form action="<?php echo BASE_URL; ?>admin" method="POST" class="d-inline-block"><input type="hidden" name="action" value="delete_news"><?php csrf_input(); ?><input type="hidden" name="id" value="<?php echo (int)$_GET['id']; ?>"><button type="submit" class="btn btn-danger">Yes, Delete</button></form><a href="<?php echo BASE_URL; ?>admin?view=news" class="btn btn-secondary ms-2">Cancel</a></div></div>
            <?php break;
            case 'users': ?>
                <div class="card mb-4"><div class="card-header"><h4><i class="fas fa-user-tag me-2"></i>Manage Roles</h4></div><div class="card-body"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Role Name</th><th class="text-end">Actions</th></tr></thead><tbody>
                <?php while ($role = $all_roles_res->fetch_assoc()): ?><tr><td><?php echo htmlspecialchars($role['name']); ?></td><td class="text-end"><?php if (!in_array($role['name'], ['Admin', 'Member'])): ?><a href="<?php echo BASE_URL; ?>admin?view=delete-role&id=<?php echo $role['id']; ?>" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a><?php endif; ?></td></tr><?php endwhile; ?>
                </tbody></table></div></div><div class="card-footer"><form action="<?php echo BASE_URL; ?>admin" method="POST" class="d-flex gap-2"><input type="hidden" name="action" value="add_role"><?php csrf_input(); ?><input type="text" name="role_name" class="form-control" placeholder="New Role Name" required><button type="submit" class="btn btn-warning">Create Role</button></form></div></div>
                <div class="card"><div class="card-header"><h4><i class="fas fa-users-cog me-2"></i>Assign User Roles</h4></div><div class="table-responsive"><table class="table table-hover table-striped mb-0"><thead><tr><th>User</th><th>Roles</th><th class="text-end">Actions</th></tr></thead><tbody>
                <?php while ($user = $users_res->fetch_assoc()): ?><tr><td><?php echo htmlspecialchars($user['display_name']); ?></td><td style="min-width:300px;"><form action="<?php echo BASE_URL; ?>admin" method="POST" id="form-user-<?php echo $user['id']; ?>"><input type="hidden" name="action" value="update_user_roles"><?php csrf_input(); ?><input type="hidden" name="user_id" value="<?php echo $user['id']; ?>"><div class="d-flex flex-wrap gap-3"><?php $current_user_roles = explode(', ', $user['roles'] ?? ''); $all_roles_res->data_seek(0); while ($role = $all_roles_res->fetch_assoc()): ?><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="roles[]" value="<?php echo $role['id']; ?>" id="role-<?php echo $user['id']; ?>-<?php echo $role['id']; ?>" <?php if (in_array($role['name'], $current_user_roles)) echo 'checked'; ?>><label class="form-check-label" for="role-<?php echo $user['id']; ?>-<?php echo $role['id']; ?>"><?php echo htmlspecialchars($role['name']); ?></label></div><?php endwhile; ?></div></form></td><td class="text-end"><button type="submit" form="form-user-<?php echo $user['id']; ?>" class="btn btn-sm btn-primary"><i class="fas fa-save"></i></button></td></tr><?php endwhile; ?>
                </tbody></table></div>
                <?php if ($total_pages > 1): ?><div class="card-footer"><?php echo generate_pagination_links(BASE_URL . 'admin?view=users', $current_page, $total_pages); ?></div><?php endif; ?>
                </div>
            <?php break;
            case 'downloads': ?>
                <div class="card mb-4"><div class="card-header"><h4><i class="fas fa-plus-circle me-2"></i>Upload New Download</h4></div><div class="card-body"><form action="<?php echo BASE_URL; ?>admin" method="POST" enctype="multipart/form-data"><input type="hidden" name="action" value="add_download"><?php csrf_input(); ?><div class="mb-3"><label for="project_name" class="form-label">Project Name</label><input type="text" class="form-control" id="project_name" name="project_name" required></div><div class="mb-3"><label for="version" class="form-label">Version</label><input type="text" class="form-control" id="version" name="version" placeholder="e.g., 1.2.0" required></div><div class="mb-3"><label for="description" class="form-label">Description / Changelog (Optional)</label><textarea id="description" name="description" rows="5" class="form-control"></textarea></div><div class="mb-3"><label for="download_file" class="form-label">File (.zip, .rar, .exe, etc.)</label><input class="form-control" type="file" id="download_file" name="download_file" required></div><button type="submit" class="btn btn-warning"><i class="fas fa-upload me-2"></i>Upload and Publish</button></form></div></div>
                <div class="card"><div class="card-header"><h4><i class="fas fa-list-alt me-2"></i>Manage Existing Downloads</h4></div><div class="table-responsive"><table class="table table-hover table-striped mb-0"><thead><tr><th>Project</th><th>Version</th><th>File Name</th><th>Size</th><th>Downloads</th><th>Actions</th></tr></thead><tbody>
                <?php while ($download = $downloads_res->fetch_assoc()): ?><tr><td><?php echo htmlspecialchars($download['project_name']); ?></td><td><?php echo htmlspecialchars($download['version']); ?></td><td><?php echo htmlspecialchars($download['file_path']); ?></td><td><?php echo round($download['file_size'] / 1024, 2); ?> KB</td><td><?php echo $download['download_count']; ?></td><td><a href="<?php echo BASE_URL; ?>admin?view=delete-download&id=<?php echo $download['id']; ?>" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a></td></tr><?php endwhile; ?>
                </tbody></table></div></div>
            <?php break;
            case 'delete-role': ?>
                <div class="card border-danger"><div class="card-header bg-danger text-white"><h4><i class="fas fa-exclamation-triangle me-2"></i>Confirm Role Deletion</h4></div><div class="card-body"><p>Are you sure you want to permanently delete the role: <strong><?php echo htmlspecialchars($role_name); ?></strong>? Any users with this role will be reassigned to "Member".</p><form action="<?php echo BASE_URL; ?>admin" method="POST" class="d-inline-block"><input type="hidden" name="action" value="delete_role"><?php csrf_input(); ?><input type="hidden" name="id" value="<?php echo (int)$_GET['id']; ?>"><button type="submit" class="btn btn-danger">Yes, Delete Role</button></form><a href="<?php echo BASE_URL; ?>admin?view=users" class="btn btn-secondary ms-2">Cancel</a></div></div>
            <?php break;
            case 'delete-download': ?>
                <div class="card border-danger"><div class="card-header bg-danger text-white"><h4><i class="fas fa-exclamation-triangle me-2"></i>Confirm Deletion</h4></div><div class="card-body"><p>Are you sure you want to permanently delete the download: <strong><?php echo htmlspecialchars($download_info); ?></strong>? This will also delete the file from the server.</p><form action="<?php echo BASE_URL; ?>admin" method="POST" class="d-inline-block"><input type="hidden" name="action" value="delete_download"><?php csrf_input(); ?><input type="hidden" name="id" value="<?php echo (int)$_GET['id']; ?>"><button type="submit" class="btn btn-danger">Yes, Delete</button></form><a href="<?php echo BASE_URL; ?>admin?view=downloads" class="btn btn-secondary ms-2">Cancel</a></div></div>
            <?php break;

            default:
                echo '<h4>Welcome to the Admin Panel!</h4><p>Select an option from the menu to get started.</p>';
                break;
        endswitch;
        ?>
    </main>
</div>
